sudo: required

language: java

jdk:
  - openjdk8

branches:
  only:
    - master

env:
    - MAVEN_OPTS="-Xms2048m -Xmx=2048m"
    
before_install:
    - "cd com.amitinside.tooling.chart.spider"
  
install: mvn install -DskipTests=true -e -X
