sudo: required

language: java

branches:
  only:
    - master
    
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "cd com.amitinside.tooling.chart.spider"
  
install: mvn clean package eclipse:eclipse -D eclipse.pde install -DskipTests=true -Darguments=-DskipTests
